### ISSUE TITLE
support more than 500 pages

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/exportMediaWiki2HTML#1]
at the moment, the call to "/api.php?action=query&list=allpages&aplimit=500&format=json" only supports 500 pages.
we would need a loop to continue with the next 500 pages.

My wiki only had 300+ pages, so there was no need for this.

**Comment by tpokorra** [comment]
@peschmae My question is, how many pages can you download without pagination? Is there a limit in the API?

https://www.mediawiki.org/wiki/API:Allpages
aplimit
    How many total pages to return. 
    Type: integer or max
    The value must be between 1 and 500.

So I think your pull request does not solve this issue yet. But it is a good improvement towards that goal.
And you used the word "solved" in the commit, not "fixes", otherwise this bug would have been closed automatically ;)

**Comment by peschmae** [comment]
Using the `max` keyword I got back ~600 pages, which was my whole wiki. So it seems like max  really tries to generate a list with all entries, with the risk, of the request timing out. 
But without a a larger wiki at hand, it's impossible to know for sure.

I think one could check for the presence of the `apcontinue` attribute on the response, and if it's there, start paginating

**Comment by tpokorra** [comment]
ok, that is fine with me. I did not know about `max`.

That solves this issue indeed.
