### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by maxime-esa** [SolidCharity/exportMediaWiki2HTML#20]
Hi, there is a case where a variable is used undefined:

line 195 of `exportMediaWiki2Html.py` you call DownloadImage(linkedpage, `imgpath`)

However `imgpath` is only defined conditionally, a few lines above.

If the condition is not met, you run through an exception:
```
Traceback (most recent call last):
  File "exportMediaWiki2Html.py", line 195, in <module>
    DownloadImage(linkedpage, imgpath)
NameError: name 'imgpath' is not defined
```

**Comment by tpokorra** [comment]
@maxime-esa this is about the situation where an uploaded file is linked, which is not an image?
I will have a look into this

**Comment by maxime-esa** [comment]
Thanks. To reproduce:
```
./exportMediaWiki2Html.py --url http://taste.tuxfamily.org/wiki --page 93
```

Additionally I noticed that I never get the images downloaded. For example this page does not raise the exception but the `img` folder remains empty after the download:
```
./exportMediaWiki2Html.py --url http://taste.tuxfamily.org/wiki --page 357
```

**Comment by tpokorra** [comment]
2 issues: mixing http and https for downloading the images, and the script did not support subpath /wiki yet.
Those have now been fixed.

**Comment by maxime-esa** [comment]
Thanks. Seems to work perfectly now!
