### ISSUE TITLE
issue with href link to image file in html output

### ISSUE THREAD

**Issue by mbachmann-lan** [SolidCharity/exportMediaWiki2HTML#21]
all my exported html files have wrong href links
```
<a href="Datei_Shelly1_mit_12V_betreiben_jpg.html" class="image"><img alt="Shelly1-mit-12V-betreiben.jpg" src="img/...
```

should be the same as src link
```
<a href="img/Shelly1-mit-12V-betreiben.jpg" class="image"><img alt="Shelly1-mit-12V-betreiben.jpg" src="img/...
```

Code lines 229, 230
```
else:
   linkedpage = PageTitleToFilename(parse.unquote(linkedpage))
   content = content[:pos] + linkedpage + ".html" + content[posendquote:]
```

**Comment by tpokorra** [comment]
@mbachmann-lan Thank you for your report.

for me, this works:
```[[File:Openpetra final-small.png|200px|thumb|right|openPETRA Logo]]```

becomes:

```
<a href="img/Openpetra_final-small.png" class="image"><img alt="" src="img/Openpetra_final-small.png" decoding="async" width="200" height="222" class="thumbimage" /></a>
```

Lines 229 and 230 should not be executed, but the condition should be true in line 207:

```
        if linkedpage.startswith('File:') or linkedpage.startswith('Image:'):
```

How does the Mediawiki Code look like?

**Comment by mbachmann-lan** [comment]
my wiki code is:
`[[File:Shelly1-mit-12V-betreiben.jpg]]`

and even if I change it to:
`[[File:Shelly1-mit-12V-betreiben.jpg|200px|thumb|right|Shelly Diagramm]]`

the href link still becomes: 
```
<a href="Datei_Shelly1_mit_12V_betreiben_jpg.html" class="image"><img alt="" src="img/Shelly1-mit-12V-betreiben.jpg" decoding="async" width="200" height="76" class="thumbimage"></a>
```
I'm using MediaWiki 1.38.4

**Comment by tpokorra** [comment]
Ah, you are probably using `[[Datei:Shelly1-mit-V12-betreiben.jpg]]`.
I cannot explain where the `Datei_` in href would come from otherwise.

I will fix that and I hope that solves the problem.

**Comment by mbachmann-lan** [comment]
Problem is solved, works like a charm, thank you!
