### ISSUE TITLE
Links to other pages starting with // (no protocol) are not replaced

### ISSUE THREAD

**Issue by Nicknag** [SolidCharity/exportMediaWiki2HTML#25]
Hi,
I do not know why but in all our wikis the links to other pages start with "//" instead of "http://" or "https://". This results in the link replacement not working.

This is how our links look like: "a href="//myurl.com/index.php?title=[...]"

Regards
Nick

**Comment by tpokorra** [comment]
Hello @Nicknag  I try to understand the problem.

How does the code look like in your mediawiki?

eg. `[[My other page]]` should work.

or do you have a link like `//myurl.com/index.php?title=` already in your code?

Is your wiki a public wiki, or can you reproduce this behaviour in a public wiki?

**Comment by Nicknag** [comment]
Hi @tpokorra 

the wiki is not public, but here is an example and how it looks at the different locations:

Wikicode:
`* [[DB Clone]]`

HTML (show source in Chrome)
`<a href="/index.php?title=DB_Clone" title="DB Clone">DB Clone</a>`

print(content) before "while url_title in content:"
`<a href="//url.to.wiki/index.php?title=DB_Clone" title="DB Clone">DB Clone</a>`


As a workaround I have added the last replace as shown here but I think this can be done in a nicer way:
```
    protocol = "http"
    
    if url_title not in content:
        url_title = url_title.replace("http://", "https://")
        protocol = "https"
    
    # add protocol to the links
    if url_title not in content:
        content = content.replace('a href="//', 'a href="' + protocol + '://')
```

Also links like https://example.org/wiki/Page_title do not work (see https://www.mediawiki.org/wiki/Manual:Short_URL). But thats another problem.

**Comment by Nicknag** [comment]
Thank you for the nice script. I tried the new code on our wiki and everything works as expected.
